# Generated by Django 5.0.3 on 2024-04-25 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_persona_dep_id_remove_persona_per_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Mun_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.municipio'),
        ),
    ]
