# Generated by Django 5.0.3 on 2024-04-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_persona_per_apellido_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Perfil_Persona',
        ),
    ]
