# Generated by Django 5.0.3 on 2024-08-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_departamento_options_alter_municipio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={},
        ),
        migrations.AlterModelTable(
            name='departamento',
            table=None,
        ),
        migrations.AlterModelTable(
            name='municipio',
            table=None,
        ),
    ]
