# Generated by Django 5.0.3 on 2024-04-26 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='Mun_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='Per_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.persona'),
        ),
    ]
