# Generated by Django 5.0.3 on 2024-04-28 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='Per_nombre',
        ),
    ]
