# Generated by Django 5.0.3 on 2024-04-28 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_remove_empleado_per_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='Persona',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='empleados.persona'),
            preserve_default=False,
        ),
    ]
