# Generated by Django 5.0.3 on 2024-05-20 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_empleado_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Per_telefono',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='Telefono'),
        ),
    ]
