# Generated by Django 5.0.3 on 2024-05-19 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_alter_cliente_per_nombre'),
        ('transacciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='factura',
        #     name='Cl_codigo',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.cliente', verbose_name='Cliente'),
        # ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('Com_codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Compra codigo')),
                ('Com_fechaGeneracion', models.DateField(auto_now_add=True, verbose_name='Fecha generacion')),
                ('Com_subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal')),
                ('Com_precioTotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio total')),
                ('Com_IVA', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='IVA')),
                ('Prov_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.sedeproveedor', verbose_name='Proveedor')),
                ('Usr_codigo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('Ven_codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Venta codigo')),
                ('Ven_fechaGeneracion', models.DateField(auto_now_add=True, verbose_name='Fecha generacion')),
                ('Ven_subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal')),
                ('Ven_precioTotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio total')),
                ('Ven_IVA', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='IVA')),
                ('Cl_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.cliente', verbose_name='Cliente')),
                ('Usr_codigo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Ventas',
            },
        ),
    ]
