# Generated by Django 5.0.3 on 2024-08-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_remove_compra_prov_codigo_compra_cl_codigo'),
        ('transacciones', '0003_alter_compra_table_alter_venta_table'),
    ]

    operations = [
    ]
