# Generated by Django 5.0.3 on 2024-08-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_merge_20240820_0227'),
    ]

    operations = [
        # migrations.AlterModelTable(
        #     name='compra',
        #     table='Compra',
        # ),
        # migrations.AlterModelTable(
        #     name='venta',
        #     table='Venta',
        # ),
    ]
