# Generated by Django 5.0.3 on 2024-08-27 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0005_alter_compra_table_alter_venta_table'),
    ]

    operations = [
        # migrations.AlterModelTable(
        #     name='compra',
        #     table='Compra',
        # ),
        # migrations.AlterModelTable(
        #     name='venta',
        #     table='Venta',
        # ),
    ]
