# Generated by Django 5.0.3 on 2024-05-20 04:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0005_alter_persona_per_telefono'),
        ('login', '0006_rename_persona_perfil_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Cl_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Cl_obligacion', models.CharField(max_length=100, verbose_name='Obligacion tributaria')),
                ('Per_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.persona')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('Prov_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Prov_NIT', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='NIT proveedor')),
                ('Prov_razonSocial', models.CharField(max_length=100, verbose_name='Razon social proveedor')),
                ('Prov_direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('Prov_telefono', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='Telefono')),
                ('Prov_correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('Mun_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='SedeProveedor',
            fields=[
                ('Provs_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Provs_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Provs_direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('Provs_telefono', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='Telefono')),
                ('Mun_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.municipio', verbose_name='Municipio')),
                ('Prov_razonSocial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.proveedor', verbose_name='Razon social Proveedor')),
            ],
            options={
                'verbose_name': 'Sede Proveedor',
                'verbose_name_plural': 'Sede Proveedores',
                'db_table': 'SedeProveedor',
            },
        ),
    ]
