# Generated by Django 5.0.3 on 2024-05-20 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_persona_per_telefono'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Per_nombre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empleados.persona'),
        ),
    ]
