# Generated by Django 5.0.3 on 2024-05-19 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_alter_cliente_per_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='Prov_telefono',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='sedeproveedor',
            name='Provs_telefono',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='Telefono'),
        ),
    ]
