# Generated by Django 5.0.3 on 2024-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0004_remove_cliente_cl_obligacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Per_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
