# Generated by Django 5.0.3 on 2024-06-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0005_alter_cliente_per_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Per_nombre',
            new_name='Cl_nombre',
        ),
    ]
