# Generated by Django 5.0.3 on 2024-08-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0004_alter_proveedor_prov_telefono_and_more'),
        ('terceros', '0006_rename_per_nombre_cliente_cl_nombre'),
    ]

    operations = [
    ]
