# Generated by Django 5.0.3 on 2024-05-20 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0006_rename_persona_perfil_persona'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Prod_codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de producto')),
                ('Prod_nombre', models.CharField(max_length=60, verbose_name='Nombre producto')),
                ('Prod_precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio unitario')),
                ('Prod_cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('Prod_IVA', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='IVA')),
                ('Emp_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.proveedor', verbose_name='Empresa')),
                ('Mun_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
    ]
