# Generated by Django 5.0.3 on 2024-08-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_usr_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Emp_codigo',
        ),
    ]
