# Generated by Django 5.0.3 on 2024-04-25 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('Dep_codigo', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('Dep_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('Mun_codigo', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('Mun_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Dep_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ubicacion.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'Municipio',
            },
        ),
    ]
