# Generated by Django 5.0.3 on 2024-04-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='Dep_codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='Mun_codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
